spec:
  destination:
    server: https://kubernetes.default.svc

prometheus:
  resources:
    limits:
      cpu:
      memory:
    requests:
      cpu:
      memory:
  server:
    persistentVolume:
      storageClass: efs-sc
      volumeName: efs-prometheus
      size: 8Gi
    serviceAccounts:
      roleArn: ""