apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: grafana
  namespace: monitoring
spec:
  serviceRef:
    name: grafana
    port: 80
  targetType: ip
  targetGroupARN: {{ .Values.grafana.targetGroupARN }}
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: influxdb
  namespace: monitoring
spec:
  serviceRef:
    name: influxdb
    port: 81
  targetType: ip
  targetGroupARN: {{ .Values.influxdb.targetGroupARN }}
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceRef:
    name: prometheus
    port: 81
  targetType: ip
  targetGroupARN: {{ .Values.influxdb.targetGroupARN }}